### PR TITLE
add more alphanumeric mappings

### PR DESCRIPTION
**Pull request by onebeartoe**

### CODE REVIEW

**Comment by FDelporte** [comment]
Thanks @onebeartoe for adding the extra LED characters!
Out of personal interest: what are you building with this example?

**Comment by FDelporte** [comment]
Fixed one character and did some minor tweaks. Looks good, thanks @onebeartoe, is merged

**Comment by onebeartoe** [comment]
Hi Frank!  Thanks and no problem.  I am using this code in a work in progress project:

https://github.com/onebeartoe/electronics/tree/master/single-board-computers/raspberry-pi/spi/max7219/led-matrix/8x8/web-app

It is pretty  much a Webified version of this code.

**Comment by FDelporte** [comment]
> I am using this code in a work in progress project

Thanks for the info! When finished, can you share screenshot/video/photo? Always nice if we can add example uses in https://pi4j.com/blog/ or https://pi4j.com/featured-projects/

**Comment by onebeartoe** [comment]
@FDelporte the documentation and code is updated; same above link.

**Comment by FDelporte** [comment]
> @FDelporte the documentation and code is updated; same above link.

Thanks @onebeartoe! I published a post on https://pi4j.com/blog/2024/20240417_led_matrix_max7219_spi_web/

**Comment by onebeartoe** [comment]
Sweet, thank you!

**Pull request merged**
